//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobSearcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bug_magnifying_glass_icon {
            get {
                object obj = ResourceManager.GetObject("bug_magnifying_glass_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To whom it may concern,
        ///For the 9 years following completion of a Master of Science in Computer Science, I have been writing software in both UI/UX and backend layers in both Windows and Linux environments.  Languages I’ve used at a professional level include C#, C++/C, Java and Python as well as JavaScript, CSS and *ml, and look forward to learning others. I have experience with CVS, SVN, Git and Mercurial version control systems.
        ///
        ///Some other tools I have used recently include Visual Studio, TeamCity (b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CoverLetter {
            get {
                return ResourceManager.GetString("CoverLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.craiglist.org/about/sites.
        /// </summary>
        public static string CraigslistBaseUrl {
            get {
                return ResourceManager.GetString("CraigslistBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search/sof?query=c%23&amp;is_telecommuting=1.
        /// </summary>
        public static string CraigslistQueryString {
            get {
                return ResourceManager.GetString("CraigslistQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.dice.com.
        /// </summary>
        public static string DiceBaseUrl {
            get {
                return ResourceManager.GetString("DiceBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jobs/advancedResult.html?for_one=c%23&amp;for_all=&amp;for_exact=&amp;for_none=&amp;for_jt=&amp;for_com=&amp;for_loc=&amp;sort=date&amp;telecommute=true&amp;limit=1000.
        /// </summary>
        public static string DiceQueryString {
            get {
                return ResourceManager.GetString("DiceQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.indeed.com.
        /// </summary>
        public static string IndeedBaseUrl {
            get {
                return ResourceManager.GetString("IndeedBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jobs?q=c%23+remote&amp;sort=date&amp;limit=5555.
        /// </summary>
        public static string IndeedQueryString {
            get {
                return ResourceManager.GetString("IndeedQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.monster.com.
        /// </summary>
        public static string MonsterBaseUrl {
            get {
                return ResourceManager.GetString("MonsterBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jobs/search/?q=c__23-remote.
        /// </summary>
        public static string MonsterQueryString {
            get {
                return ResourceManager.GetString("MonsterQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ArrayOfString xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///&lt;/ArrayOfString&gt;.
        /// </summary>
        public static string SearchHistory {
            get {
                return ResourceManager.GetString("SearchHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://stackoverflow.com/.
        /// </summary>
        public static string StackOverFlowBaseUrl {
            get {
                return ResourceManager.GetString("StackOverFlowBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jobs/remote-developer-jobs-using-c%23?sort=p.
        /// </summary>
        public static string StackOverFlowQueryString {
            get {
                return ResourceManager.GetString("StackOverFlowQueryString", resourceCulture);
            }
        }
    }
}
