//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearcherTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobSearcherTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestHtmlFiles/CraigslistCities.html.
        /// </summary>
        internal static string CraigslistCitiesFileString {
            get {
                return ResourceManager.GetString("CraigslistCitiesFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestHtmlFiles/CraigslistJob.html.
        /// </summary>
        internal static string CraigslistJobString {
            get {
                return ResourceManager.GetString("CraigslistJobString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestHtmlFiles/CraigslistList.html.
        /// </summary>
        internal static string CraigslistListFileString {
            get {
                return ResourceManager.GetString("CraigslistListFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestHtmlFiles/CraigslistReply.html.
        /// </summary>
        internal static string CraigslistReplyFileString {
            get {
                return ResourceManager.GetString("CraigslistReplyFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestHtmlFiles/DiceJob.html.
        /// </summary>
        internal static string DiceJobString {
            get {
                return ResourceManager.GetString("DiceJobString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestHtmlFiles/DiceList.html.
        /// </summary>
        internal static string DiceListFileString {
            get {
                return ResourceManager.GetString("DiceListFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestHtmlFiles/IndeedJob.html.
        /// </summary>
        internal static string IndeedJobString {
            get {
                return ResourceManager.GetString("IndeedJobString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestHtmlFiles/IndeedList.html.
        /// </summary>
        internal static string IndeedListFileString {
            get {
                return ResourceManager.GetString("IndeedListFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestHtmlFiles/MonsterJob.html.
        /// </summary>
        internal static string MonsterJobString {
            get {
                return ResourceManager.GetString("MonsterJobString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestHtmlFiles/MonsterList.html.
        /// </summary>
        internal static string MonsterListFileString {
            get {
                return ResourceManager.GetString("MonsterListFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestHtmlFiles/StackOverflowJob.html.
        /// </summary>
        internal static string StackOverflowJobString {
            get {
                return ResourceManager.GetString("StackOverflowJobString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestHtmlFiles/StackOverflowList.html.
        /// </summary>
        internal static string StackOverflowListFileString {
            get {
                return ResourceManager.GetString("StackOverflowListFileString", resourceCulture);
            }
        }
    }
}
